name: catalog-api-build-template-unittest

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/catalog-service/api/*

trigger: none
pr: none

variables:
  dotnetSdkVersion: "8.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scFood
  appPath: src/services/catalog-service/api/
  appTests: apps/catalog-api/api-tests/

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "Build"
    displayName: "Build"
    jobs:
      - job: "Build"
        steps:
          - template: templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(appPath)

      - job: test_dotnet
        displayName: "Test"

        steps:
          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: "test"
              projects: "$(appTests)/*.csproj"
              arguments: "--configuration $(buildConfiguration)"