name: catalog-api-ci-cd-mi

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/catalog-service/api/*

trigger: none
pr: none

variables:
  dotnetSdkVersion: "8.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scWorkload
  appPath: src/services/catalog-service/api/
  appService: food-catalog-api-yaml

pool:
  vmImage: ubuntu-latest

stages: 
  - stage: Build
    displayName: Build and Update Config
    
    jobs:
      - job: Build
        steps:
          - task: FileTransform@1
            displayName: Update Configuration
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)/$(appPath)'
              fileType: 'json'
              targetFiles: '**/appsettings.json'

          - template: templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(appPath)

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    
    jobs:
      - deployment: Deploy
        displayName: Deploy to AppService
        environment: $(appService)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appService)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azSubscription)
                    appType: "webApp"
                    WebAppName: $(appService)
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
