name: catalog-ci-sonar-cloud

trigger: none
pr: none

variables:
  dotnetSdkVersion: "8.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scFood
  appPath: src/services/catalog-service/api/
  appTests: apps/catalog-api/api-tests/
  sonarCon: scSonarCloud
  sonaOrg: integrations-development
  sonarKey: integrations-development_az-400
  sonarProj: az-400


pool:
  name: az-pool

steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
    inputs:
      version: "$(dotnetSdkVersion)"
  
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.4.1'
    inputs:
      versionSpec: 4.4.1

  - task: DotNetCoreCLI@2
    displayName: "Restore project dependencies"
    inputs:
      command: "restore"
      projects: '$(appPath)/*.csproj'

  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis configuration'
    inputs:
      SonarCloud: '$(sonarCon)'
      organization: '$(sonaOrg)'
      scannerMode: 'MSBuild'
      projectKey: '$(sonarKey)'
      projectName: '$(projName)'

  - task: DotNetCoreCLI@2
    displayName: "Build the project - $(buildConfiguration)"
    inputs:
      command: "build"
      arguments: "--no-restore --configuration $(buildConfiguration)"
      projects: "$(appPath)/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Run unit tests - $(buildConfiguration)"
    inputs:
      command: "test"
      arguments: '--no-build --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura%2copencover" /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
      publishTestResults: true
      projects: "appTests/*.csproj"

  - task: SonarCloudAnalyze@1
    displayName: "Run SonarCloud code analysis"

  - task: SonarCloudPublish@1
    displayName: "Publish SonarCloud quality gate results"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"