name: "catalog-ci"

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/catalog-service/api/*

trigger: none
pr: none

variables:
  buildConfiguration: Release
  appPath: src/services/catalog-service/api/

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "Build"
    jobs:
      - job: "Build"
        displayName: "Build Catalog Package"

        steps:
          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: "sdk"
              version: "8.x"

          - task: DotNetCoreCLI@2
            displayName: Build .NET
            inputs:
              command: build
              projects: "$(appPath)/catalog-service.csproj"
              arguments: "--configuration $(buildConfiguration)"

          - task: DotNetCoreCLI@2
            displayName: Publish .NET
            inputs:
              command: publish
              publishWebProjects: true
              arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: True

          - task: PublishPipelineArtifact@1
            displayName: "Publish Artifact: catalog-drop"
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifactName: catalog-drop
