name: food-app-provision

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  azSubscription: scFood
  rg: az400-dev
  vault: az400-vault-dev  
  templateFile: deploy/bicep/food-app.bicep

stages:
- stage: "Provision"
  jobs:
    - job: "Provision"
      steps:
        - task: AzureKeyVault@1
          displayName: 'Azure Key Vault: $(vault)'
          inputs:
            azureSubscription: $(azSubscription)
            KeyVaultName: $(vault)            
        - task: AzureCLI@2
          displayName: 'Provision AppService'
          inputs:
            azureSubscription: '$(azSubscription)'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment group create --resource-group $(rg) \
                --template-file $(templateFile) \
                --parameters \
                  appName=food-app-dev \
                  rgLocation=westeurope \
                  acaEnvName= az400acrdev \
                  acrName=$(acrName) \
                  acrPwd=$(acrPassword) \
                  catalogName='catalog-service' \
                  catalogImage='catalog-service' \
                  shopName='food-shop' \
                  shopImage='food-shop' \
                  orderName='order-service' \
                  orderImage='order-service' 
