name: orders-ci

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/order-service/*

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  proj: az-400
  feed: food-packages
  dotnetSdkVersion: "8.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scFood
  appPath: src/services/order-service/

stages:
  - stage: "Build"
    jobs:
      - job: "Build"
        displayName: "Build with Dependencies"
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
            inputs:
              version: "$(dotnetSdkVersion)"
          - task: NuGetToolInstaller@1
            inputs:
              checkLatest: true
          - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
            displayName: "Write build info"
          - task: NuGetCommand@2
            displayName: "Restore project dependencies"
            inputs:
              command: 'restore'
              restoreSolution: $(appPath)/*.csproj
              feedsToUse: 'select'
              vstsFeed: $(proj)/$(feed)
              includeNuGetOrg: true 
          - task: DotNetCoreCLI@2
            displayName: "Build"
            inputs:
              command: 'build'
              projects: '$(appPath)/*.csproj'
              arguments: '--no-restore --configuration $(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: "Publish"
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '$(appPath)/*.csproj'
              arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: drop
            displayName: "Publish Artifact: drop"