name: orders-ci-docker-img

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/services/order-service/*

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  proj: az-400
  dotnetSdkVersion: "8.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scFood
  acr: scACR
  appPath: src/services/order-service/
  vault: az400-vault-dev
  imageName: 'order-service'

stages:
  - stage: "Build"
    jobs:
      - job: "Build"
        steps:
          - task: AzureKeyVault@1
            displayName: 'Azure Key Vault: $(vault)'
            inputs:
              azureSubscription: $(azSubscription)
              KeyVaultName: $(vault)

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acr)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              containerRegistry: $(acr)
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '$(appPath)dockerfile'
              tags: 'latest'
              arguments: '--build-arg PAT=$(PATToken)'
              
          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(acr)