name: catalog-ci-cd-bicep

trigger: none
pr: none

variables:
  dotnetSdkVersion: "8.x"
  buildConfiguration: Release
  releaseBranchName: master
  azCon: scIdentityWorkload
  appPath: src/services/catalog-service/api/
  appService: catalog-service-bicep
  templateFile: deploy/bicep/webapp-windows.bicep
  rg: az400-dev
  loc: 'westeurope'
  subscriptionId: 78033352-805c-4acd-af80-f8f95083268d

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: BnP
    displayName: Build and Provision
    jobs:
      - job: "Build"
        steps:
          - template: templates/t-net-build.yaml
            parameters:
              cfg: $(buildConfiguration)
              folder: $(appPath)
              project: catalog-service
      
      - job: Provision
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: $(azCon)
            subscriptionId: '$(subscriptionId)'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(rg)'
            location: '$(loc)'
            templateLocation: 'Linked artifact'
            csmFile: '$(templateFile)'
            deploymentMode: 'Incremental'
            overrideParameters: '-webAppName $(appService)'

  - stage: Deploy
    displayName: Deploy
    dependsOn: BnP

    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appService)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azCon)
                    appType: "webApp"
                    WebAppName: "$(appService)"
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
