name: provision-azure-cli

trigger: none
pr: none

variables:
  script: "deploy/cli/create-orders-topic-func.sh"
  azSubscription: scFood
  environment: dev

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Provision
    jobs:
      - job: Provision
        displayName: Provision Azure CLI
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azSubscription)
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: '$(System.DefaultWorkingDirectory)/$(script)'
              arguments: '$(environment)'