name: spfx-ci-cd

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - src/teams/food-list/*

trigger: none
pr: none

variables:
  package: foodlist-wp.sppkg
  appPath: src/teams/food-list/ 
  environment: m365-integrationsonline-dev
  # set pipeline vars: username, password

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build SPFx Package
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 14.x
            displayName: Install Node.js
          
          - task: Cache@2
            displayName: Cache node_modules
            inputs:
              key: '$(System.DefaultWorkingDirectory)/$(appPath)/package-lock.json'
              path: '$(System.DefaultWorkingDirectory)/$(appPath)/node_modules'
              cacheHitVar: 'CacheRestored'

          - task: CmdLine@2
            displayName: npm install
            condition: eq(variables['CacheRestored'],False)
            inputs:
              script: "npm install"
              workingDirectory: "$(appPath)/"              

          - task: gulp@1
            displayName: "gulp bundel"
            inputs:
              gulpFile: "$(appPath)/gulpfile.js"
              targets: "bundle"
              arguments: "--ship"
              enableCodeCoverage: false

          - task: gulp@1
            displayName: "gulp package solution"
            inputs:
              gulpFile: "$(appPath)/gulpfile.js"
              targets: "package-solution"
              arguments: "--ship"

          - task: CopyFiles@2
            displayName: "Copy Files to: $(build.artifactstagingdirectory)/spfx"
            inputs:
              Contents: "$(appPath)/sharepoint/solution/*.sppkg"
              TargetFolder: "$(build.artifactstagingdirectory)/spfx"

          - task: PublishBuildArtifacts@1
            displayName: "Publish artifacts: spfxdrop"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"

  - stage: Deploy
    displayName: Deploy to M365
    dependsOn: Build
    variables:
      tenant: d92b247e-90e0-4469-a129-6a32866c0d0a

    jobs:
      - deployment: DeployM365Dev
        displayName: Deploy to M365
        environment: m365-integrationsonline-dev
        strategy:
          runOnce:
            deploy:
              steps:
            
              - task: NodeTool@0
                displayName: 'Use Node 14.x'
                inputs:
                  versionSpec: 14.x
                  
              - task: Npm@1
                displayName: 'npm i -g @pnp/cli-microsoft365'
                inputs:
                  command: custom
                  verbose: false
                  customCommand: 'install -g @pnp/cli-microsoft365@6.0.0'
              
              - script: m365 login --authType password -u $(username) -p $(password) --tenant $(tenant)                 
                displayName: 'Connect to M365'              

              - script: 'm365 spo app add -p $(Agent.BuildDirectory)/drop/spfx/src/teams/food-list/sharepoint/solution/$(package) --overwrite'
                displayName: 'Upload to App Catalog'

              - script: 'm365 spo app deploy --name $(package)'
                displayName: 'Deploy App'

    
      - deployment: DeployM365Staging
        displayName: Deploy to M365
        environment: m365-integrationsonline-staging
        strategy:
          runOnce:
            deploy:
              steps:
            
              - task: NodeTool@0
                displayName: 'Use Node 14.x'
                inputs:
                  versionSpec: 14.x
                  
              - task: Npm@1
                displayName: 'npm i -g @pnp/cli-microsoft365'
                inputs:
                  command: custom
                  verbose: false
                  customCommand: 'install -g @pnp/cli-microsoft365@6.0.0'
              
              - script: m365 login --authType password -u $(username) -p $(password) --tenant $(tenant)                 
                displayName: 'Connect to M365'              

              - script: 'm365 spo app add -p $(Agent.BuildDirectory)/drop/spfx/src/teams/food-list/sharepoint/solution/$(package) --overwrite'
                displayName: 'Upload to App Catalog'

              - script: 'm365 spo app deploy --name $(package)'
                displayName: 'Deploy App'                               